config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :movies
  resources :lists, only: [:index, :show, :new, :create]
  resources :bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
  end

  def new
  end

  def destroy
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner banner-image">
  <div class="container">
    <h1>My <strong>Movie Lists</strong></h1>
    <p>Documenting the movies I have watsched</p>
    <!--<a class="btn btn-flat" href="#">Apply now</a> -->

    <div class="banner-list">
      <h1>My List</h1>
      <ul class="list-group list-group-horizontal mb-2 ">
        <% @lists.each do |list| %>
          <li class="list-group-item"><%= link_to list.name, list_path(list) %></li>
        <% end %>

        <li class="list-group-item list-bt">
          <i class="fa-solid fa-plus" style="color: white;"></i>
          <%= link_to "Create a new list", new_list_path %>
        </li>
      </ul>

    </div>

  </div>


</div>

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to lists", lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%# Show the movies %>

<ul class="list-group mb-2">
  <% @list.movies.each do |movie| %>
    <li class="list-group-item"><%= movie.title %></li>
  <% end %>
</ul>

<%= link_to "Back to lists", lists_path %>